
GET http://localhost:3000/v1/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQyOTYzMDYsImV4cCI6MTU5NDI5OTkwNiwiYXVkIjoiNWYwNmUwMjMyMGJmYzkwNTQ3MTJjZWUyIiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.yyYb5_wPj92eol8y7atJq9xFjRW8YiA-zOQEVhDGJ16rd-hI7bLfjXR4cwdvuLLaIDem4DoPTyb4O6RXMJIgLg

### Register Route
POST  http://localhost:3000/v1/auth/register
Content-Type: application/json

{
    "firstname": "LIVINGSTONE",
    "lastname": "Wachira",
    "email": "livingstonenjaria4@gmail.com",
    "phone": "+97338068374",
    "password": "12345678"
}

### Login Route
POST  http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email": "livingstonenjaria4@gmail.com",
    "password": "12345678"
}

### Refresh Token Route
POST  http://localhost:3000/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQyOTYyNjEsImV4cCI6MTYyNTg1Mzg2MSwiYXVkIjoiNWYwNmUwMjMyMGJmYzkwNTQ3MTJjZWUyIiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.JzLccR9uxyPBW9PQxF17DAhK-T6zVSWEzUMKZV3WFLkGkhPEtrsrDK_y9HCiok12u-urubMp1_ZiBSGOeZIi3A"
}

### Forgot Password Route
POST  http://localhost:3000/v1/auth/forgot-password
# Content-Type: 'application/json'

### Reset Password Route
POST  http://localhost:3000/v1/auth/reset-password
# Content-Type: 'application/json'

### Logout Route
DELETE   http://localhost:3000/v1/auth/logout
# Content-Type: 'application/json'