
GET http://localhost:5000/v1/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQyOTYzMDYsImV4cCI6MTU5NDI5OTkwNiwiYXVkIjoiNWYwNmUwMjMyMGJmYzkwNTQ3MTJjZWUyIiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.yyYb5_wPj92eol8y7atJq9xFjRW8YiA-zOQEVhDGJ16rd-hI7bLfjXR4cwdvuLLaIDem4DoPTyb4O6RXMJIgLg

### Register Route
POST  http://localhost:5000/v1/auth/register
Content-Type: application/json

{
    "firstname": "LIVINGSTONE",
    "lastname": "Wachira",
    "email": "livingstonenjaria4@gmail.com",
    "phone": "+97338068374",
    "password": "12345678"
}

### Login Route
POST  http://localhost:5000/v1/auth/login
Content-Type: application/json

{
    "email": "livingstonenjaria4@gmail.com",
    "password": "12345678"
}

### Refresh Token Route
POST  http://localhost:5000/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ0NDQ0NTgsImV4cCI6MTYyNjAwMjA1OCwiYXVkIjoiNWYwOTQzYTYxMGFiNjFkZTEwZTc3NjA1IiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.Ku_5tQXZ_QDm94zu_g67dy44AFuP7Bq1dgskWUAz34rJjoz0_WRwVDbVE9Wi4-l5DAwKI5oyAQ-q6c59u9UgTA"
}

### Forgot Password Route
POST  http://localhost:5000/v1/auth/forgot-password
# Content-Type: 'application/json'

### Reset Password Route
POST  http://localhost:5000/v1/auth/reset-password
# Content-Type: 'application/json'

### Logout Route
DELETE   http://localhost:5000/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ1MDM3ODMsImV4cCI6MTYyNjA2MTM4MywiYXVkIjoiNWYwOTQzYTYxMGFiNjFkZTEwZTc3NjA1IiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.SxY0-6zP_P8JOF1LGz2cvYxzF7oc59_WNv4ucdHWd0uHYJpXdTHgvUeyA_sQ6dL3pnKg35RsV22eVxYw3Et9MQ"
}