
GET http://localhost:5000/v1/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQyOTYzMDYsImV4cCI6MTU5NDI5OTkwNiwiYXVkIjoiNWYwNmUwMjMyMGJmYzkwNTQ3MTJjZWUyIiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.yyYb5_wPj92eol8y7atJq9xFjRW8YiA-zOQEVhDGJ16rd-hI7bLfjXR4cwdvuLLaIDem4DoPTyb4O6RXMJIgLg

### Register Route
POST  http://localhost:5000/v1/auth/register
Content-Type: application/json

{
    "firstname": "LIVINGSTONE",
    "lastname": "Wachira",
    "email": "livingstonenjaria4@gmail.com",
    "phone": "+97338068374",
    "password": "12345678"
}

### Login Route
POST  http://localhost:5000/v1/auth/login
Content-Type: application/json

{
    "email": "livingstonenjaria4@gmail.com",
    "password": "12345678"
}

### Refresh Token Route
POST  http://localhost:5000/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ1MDUwMzEsImV4cCI6MTYyNjA2MjYzMSwiYXVkIjoiNWYwYTM3M2Q2MTRjN2EwNzZhYzZkMzE1IiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.DkhLFltqJYE3h5HdgyiK7vsUWkm44dmklhRZaaay7BHINf1ZIe5O-GAhuqjijNREIwV5yJFncP04zQH7zMiiFg"
}

### Forgot Password Route
POST  http://localhost:5000/v1/auth/forgot-password
# Content-Type: 'application/json'

### Reset Password Route
POST  http://localhost:5000/v1/auth/reset-password
# Content-Type: 'application/json'

### Logout Route
DELETE   http://localhost:5000/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ1MDUwNzksImV4cCI6MTYyNjA2MjY3OSwiYXVkIjoiNWYwYTM3M2Q2MTRjN2EwNzZhYzZkMzE1IiwiaXNzIjoiZ29vZGVhdHMuY29tIn0.COwopQgCeBMXpawTEJdPN-c38KmYpwmippl091kuQ6T5-KI99AqNC-u8FtK2rfFu0RmymNGFt3fdFPjND4AcQg"
}